project:
  type: website
  output-dir: docs

website:
  title: "Griffin Shelor"
  navbar:
    background: "#8A8D8F"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    backgroundcolor: "#041E42"
    fontcolor: "#FFFFFF"
    linkcolor: "#8A8D8F"
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

